# Generated by Django 3.1.2 on 2020-10-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese un Nombre', max_length=100)),
                ('apellido', models.CharField(help_text='Ingrese un Apellido', max_length=100)),
                ('edad', models.IntegerField(help_text='Ingrese una edad', null=True)),
                ('direccion', models.CharField(help_text='Ingrese una Direccion', max_length=100)),
                ('correo', models.EmailField(help_text='Ingrese un correo electronico', max_length=100)),
                ('contraseña', models.CharField(help_text='Ingrese una Contraseña', max_length=60)),
            ],
        ),
    ]
