# Generated by Django 3.1.2 on 2020-10-20 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compañia',
            fields=[
                ('nombre_compañia', models.UUIDField(default=uuid.uuid4, help_text='Indique el Nombre de la Compañia', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, help_text='Indique el Codigo del VideoJuego', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el Nombre del VideoJuego', max_length=60)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('juego', models.CharField(choices=[('E', 'Todos'), ('E+10', 'Todos + 10'), ('T', 'Adolecentes'), ('M', 'Maduro +17'), ('A', 'Adultos +18'), ('RP', 'Clasificacion Pendiente')], default='E', max_length=4)),
                ('compañia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.compañia')),
            ],
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
