# Generated by Django 3.1.2 on 2020-10-20 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201019_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='compañia',
        ),
        migrations.DeleteModel(
            name='Compañia',
        ),
    ]
