# Generated by Django 3.1.2 on 2020-10-20 23:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201019_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compañia',
            fields=[
                ('id_compañia', models.UUIDField(default=uuid.uuid4, help_text='Indique el Nombre de la Compañia', primary_key=True, serialize=False)),
                ('nombre_com', models.CharField(help_text='Ingrese el Nombre de la Compañia', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='compañia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.compañia'),
        ),
    ]
